import { formatIndustryLabel, industryGroupForLabel, normalizeIndustryLabel, UNKNOWN_INDUSTRY } from "./industry";

type IndustryDisplay = {
  group: string;
  detail?: string;
};

const COMPANY_NAME_BY_CODE: Record<string, string> = {
  AAPL: "苹果",
  ABBV: "艾伯维",
  ABT: "雅培",
  ADBE: "Adobe",
  AMD: "AMD",
  AMAT: "应用材料",
  AMZN: "亚马逊",
  ANET: "Arista Networks",
  APH: "安费诺",
  ARM: "Arm",
  AVGO: "博通",
  BA: "波音",
  BABA: "阿里巴巴",
  BAC: "美国银行",
  BIDU: "百度",
  BILI: "哔哩哔哩",
  BKNG: "Booking",
  BRK_B: "伯克希尔",
  BSX: "波士顿科学",
  C: "花旗",
  CAT: "卡特彼勒",
  CELH: "Celsius",
  CMG: "Chipotle",
  CMCSA: "康卡斯特",
  COIN: "Coinbase",
  COST: "好市多",
  CRM: "赛富时",
  CSCO: "思科",
  CVX: "雪佛龙",
  DIS: "迪士尼",
  GOOG: "谷歌",
  GOOGL: "谷歌",
  IBM: "IBM",
  INTC: "英特尔",
  JD: "京东",
  JPM: "摩根大通",
  KO: "可口可乐",
  LI: "理想汽车",
  MCD: "麦当劳",
  META: "Meta",
  MDT: "美敦力",
  MRK: "默沙东",
  MSFT: "微软",
  MU: "美光科技",
  NFLX: "奈飞",
  NIO: "蔚来",
  NVO: "诺和诺德",
  NU: "Nu Holdings",
  NVDA: "英伟达",
  ORCL: "甲骨文",
  PDD: "拼多多",
  PEP: "百事",
  PFE: "辉瑞",
  PYPL: "PayPal",
  QCOM: "高通",
  SHOP: "Shopify",
  SMCI: "超微电脑",
  SBUX: "星巴克",
  SONY: "索尼",
  TME: "腾讯音乐",
  TSLA: "特斯拉",
  TSM: "台积电",
  UBER: "优步",
  WFC: "富国银行",
  WMT: "沃尔玛",
  XOM: "埃克森美孚",
  XPEV: "小鹏汽车",
  ZTS: "硕腾",

  "00005": "汇丰控股",
  "00011": "恒生银行",
  "00012": "恒基地产",
  "00016": "新鸿基地产",
  "00017": "新世界发展",
  "00027": "银河娱乐",
  "00083": "信和置业",
  "00101": "恒隆地产",
  "00119": "保利置业集团",
  "00123": "越秀地产",
  "00151": "中国旺旺",
  "00168": "青岛啤酒股份",
  "00220": "统一企业中国",
  "00285": "比亚迪电子",
  "00291": "华润啤酒",
  "00303": "伟易达",
  "00300": "美的集团",
  "00322": "康师傅控股",
  "00358": "江西铜业股份",
  "00386": "中国石油化工股份",
  "00388": "香港交易所",
  "00390": "中国中铁",
  "00688": "中国海外发展",
  "00700": "腾讯控股",
  "00728": "中国电信",
  "00762": "中国联通",
  "00857": "中国石油股份",
  "00883": "中国海洋石油",
  "00939": "建设银行",
  "00941": "中国移动",
  "00966": "中国太平",
  "00968": "信义光能",
  "00981": "中芯国际",
  "00992": "联想集团",
  "00998": "中信银行",
  "01024": "快手",
  "01066": "威高股份",
  "01088": "中国神华",
  "01093": "石药集团",
  "01099": "国药控股",
  "01109": "华润置地",
  "01128": "永利澳门",
  "01157": "中联重科",
  "01177": "中国生物制药",
  "01186": "中国铁建",
  "01209": "华润万象生活",
  "01211": "比亚迪股份",
  "01288": "农业银行",
  "01299": "友邦保险",
  "01336": "新华保险",
  "01347": "华虹半导体",
  "01357": "美图公司",
  "01364": "古茗",
  "01378": "中国宏桥",
  "01385": "上海复旦",
  "01398": "工商银行",
  "01456": "国联证券",
  "01519": "极兔速递",
  "01530": "三生制药",
  "01658": "邮储银行",
  "01766": "中国中车",
  "01772": "赣锋锂业",
  "01787": "山东黄金",
  "01800": "中国交通建设",
  "01801": "信达生物",
  "01810": "小米集团",
  "01882": "海天国际",
  "01876": "百威亚太",
  "01898": "中煤能源",
  "01913": "普拉达",
  "01928": "金沙中国",
  "01929": "周大福",
  "01963": "重庆银行",
  "01972": "太古地产",
  "01988": "民生银行",
  "02007": "碧桂园",
  "02015": "理想汽车",
  "02018": "瑞声科技",
  "02020": "安踏体育",
  "02050": "三花智控",
  "02057": "中通快递",
  "02076": "BOSS直聘",
  "02097": "蜜雪集团",
  "02202": "万科企业",
  "02208": "金风科技",
  "02269": "药明生物",
  "02313": "申洲国际",
  "02318": "中国平安",
  "02319": "蒙牛乳业",
  "02328": "中国财险",
  "02331": "李宁",
  "02333": "长城汽车",
  "02338": "潍柴动力",
  "02357": "中航科工",
  "02359": "药明康德",
  "02382": "舜宇光学科技",
  "02388": "中银香港",
  "02400": "心动公司",
  "02423": "贝壳",
  "02600": "中国铝业",
  "02601": "中国太保",
  "02607": "上海医药",
  "02611": "国泰君安",
  "02628": "中国人寿",
  "03288": "海天味业",
  "03328": "交通银行",
  "03606": "福耀玻璃",
  "03618": "重庆农商行",
  "03690": "美团",
  "03692": "翰森制药",
  "03698": "徽商银行",
  "03750": "宁德时代",
  "03800": "协鑫科技",
  "03908": "中金公司",
  "03968": "招商银行",
  "03988": "中国银行",
  "03993": "洛阳钼业",
  "04336": "应用材料",
  "06030": "中信证券",
  "06288": "迅销",
  "06618": "京东健康",
  "06690": "海尔智家",
  "06818": "光大银行",
  "06823": "香港电讯",
  "06865": "福莱特玻璃",
  "06881": "中国银河",
  "06886": "华泰证券",
  "09618": "京东集团",
  "09633": "农夫山泉",
  "09696": "天齐锂业",
  "09866": "蔚来",
  "09868": "小鹏汽车",
  "09888": "百度集团",
  "09899": "云音乐",
  "09901": "新东方",
  "09961": "携程集团",
  "09987": "百胜中国",
  "09988": "阿里巴巴",
  "09992": "泡泡玛特",
  "09999": "网易",
};

const INDUSTRY_BY_CODE: Record<string, IndustryDisplay> = {
  AAPL: { group: "电子", detail: "消费电子" },
  AMD: { group: "电子", detail: "半导体" },
  AMAT: { group: "电子", detail: "半导体" },
  AMZN: { group: "商贸零售", detail: "互联网电商" },
  APH: { group: "电子", detail: "元件" },
  ARM: { group: "电子", detail: "半导体" },
  AVGO: { group: "电子", detail: "半导体" },
  BABA: { group: "商贸零售", detail: "互联网电商" },
  BAC: { group: "银行" },
  BIDU: { group: "传媒", detail: "数字媒体" },
  BILI: { group: "传媒", detail: "数字媒体" },
  BRK_B: { group: "非银金融", detail: "多元金融" },
  BSX: { group: "医药生物", detail: "医疗器械" },
  C: { group: "银行" },
  CAT: { group: "机械设备", detail: "工程机械" },
  COIN: { group: "非银金融", detail: "证券" },
  CMCSA: { group: "传媒", detail: "电视广播" },
  COST: { group: "商贸零售", detail: "一般零售" },
  CRM: { group: "计算机", detail: "软件开发" },
  CSCO: { group: "通信", detail: "通信设备" },
  CVX: { group: "石油石化", detail: "油气开采" },
  DIS: { group: "传媒", detail: "影视院线" },
  GOOG: { group: "传媒", detail: "数字媒体" },
  GOOGL: { group: "传媒", detail: "数字媒体" },
  IBM: { group: "计算机", detail: "IT服务" },
  INTC: { group: "电子", detail: "半导体" },
  JD: { group: "商贸零售", detail: "互联网电商" },
  JPM: { group: "银行" },
  KO: { group: "食品饮料", detail: "软饮料" },
  LI: { group: "汽车", detail: "乘用车" },
  MCD: { group: "社会服务", detail: "酒店餐饮" },
  META: { group: "传媒", detail: "数字媒体" },
  MDT: { group: "医药生物", detail: "医疗器械" },
  MRK: { group: "医药生物", detail: "化学制药" },
  MSFT: { group: "计算机", detail: "软件开发" },
  MU: { group: "电子", detail: "半导体" },
  NFLX: { group: "传媒", detail: "数字媒体" },
  NIO: { group: "汽车", detail: "乘用车" },
  NVO: { group: "医药生物", detail: "化学制药" },
  NU: { group: "非银金融", detail: "多元金融" },
  NVDA: { group: "电子", detail: "半导体" },
  ORCL: { group: "计算机", detail: "软件开发" },
  PDD: { group: "商贸零售", detail: "互联网电商" },
  PEP: { group: "食品饮料", detail: "软饮料" },
  PFE: { group: "医药生物", detail: "化学制药" },
  PYPL: { group: "计算机", detail: "IT服务" },
  QCOM: { group: "电子", detail: "半导体" },
  SBUX: { group: "社会服务", detail: "酒店餐饮" },
  SMCI: { group: "计算机", detail: "计算机设备" },
  SONY: { group: "电子", detail: "消费电子" },
  TME: { group: "传媒", detail: "数字媒体" },
  TSLA: { group: "汽车", detail: "乘用车" },
  TSM: { group: "电子", detail: "半导体" },
  UBER: { group: "交通运输", detail: "物流" },
  WFC: { group: "银行" },
  WMT: { group: "商贸零售", detail: "一般零售" },
  XOM: { group: "石油石化", detail: "油气开采" },
  XPEV: { group: "汽车", detail: "乘用车" },
  ZTS: { group: "农林牧渔", detail: "动物保健" },

  "00005": { group: "银行" },
  "00011": { group: "银行" },
  "00012": { group: "房地产", detail: "房地产开发" },
  "00016": { group: "房地产", detail: "房地产开发" },
  "00017": { group: "房地产", detail: "房地产开发" },
  "00027": { group: "社会服务", detail: "旅游及景区" },
  "00083": { group: "房地产", detail: "房地产开发" },
  "00101": { group: "房地产", detail: "房地产开发" },
  "00119": { group: "房地产", detail: "房地产开发" },
  "00123": { group: "房地产", detail: "房地产开发" },
  "00151": { group: "食品饮料", detail: "休闲食品" },
  "00168": { group: "食品饮料", detail: "啤酒" },
  "00220": { group: "食品饮料", detail: "食品加工" },
  "00285": { group: "电子", detail: "消费电子" },
  "00291": { group: "食品饮料", detail: "啤酒" },
  "00303": { group: "电子", detail: "消费电子" },
  "00300": { group: "家用电器", detail: "白色家电" },
  "00322": { group: "食品饮料", detail: "食品加工" },
  "00358": { group: "有色金属", detail: "工业金属" },
  "00386": { group: "石油石化", detail: "炼化及贸易" },
  "00388": { group: "非银金融", detail: "证券" },
  "00390": { group: "建筑装饰", detail: "基础建设" },
  "00688": { group: "房地产", detail: "房地产开发" },
  "00700": { group: "传媒", detail: "游戏" },
  "00728": { group: "通信", detail: "通信服务" },
  "00762": { group: "通信", detail: "通信服务" },
  "00857": { group: "石油石化", detail: "油气开采" },
  "00883": { group: "石油石化", detail: "油气开采" },
  "00939": { group: "银行" },
  "00941": { group: "通信", detail: "通信服务" },
  "00966": { group: "非银金融", detail: "保险" },
  "00968": { group: "电力设备", detail: "光伏设备" },
  "00981": { group: "电子", detail: "半导体" },
  "00992": { group: "计算机", detail: "计算机设备" },
  "00998": { group: "银行" },
  "01024": { group: "传媒", detail: "数字媒体" },
  "01066": { group: "医药生物", detail: "医疗器械" },
  "01088": { group: "煤炭", detail: "煤炭开采" },
  "01093": { group: "医药生物", detail: "化学制药" },
  "01099": { group: "医药生物", detail: "医药商业" },
  "01109": { group: "房地产", detail: "房地产开发" },
  "01128": { group: "社会服务", detail: "旅游及景区" },
  "01157": { group: "机械设备", detail: "工程机械" },
  "01177": { group: "医药生物", detail: "化学制药" },
  "01186": { group: "建筑装饰", detail: "基础建设" },
  "01209": { group: "房地产", detail: "房地产服务" },
  "01211": { group: "汽车", detail: "乘用车" },
  "01288": { group: "银行" },
  "01299": { group: "非银金融", detail: "保险" },
  "01336": { group: "非银金融", detail: "保险" },
  "01347": { group: "电子", detail: "半导体" },
  "01357": { group: "计算机", detail: "软件开发" },
  "01364": { group: "社会服务", detail: "酒店餐饮" },
  "01378": { group: "有色金属", detail: "工业金属" },
  "01385": { group: "电子", detail: "半导体" },
  "01398": { group: "银行" },
  "01456": { group: "非银金融", detail: "证券" },
  "01519": { group: "交通运输", detail: "物流" },
  "01530": { group: "医药生物", detail: "生物制品" },
  "01658": { group: "银行" },
  "01766": { group: "机械设备", detail: "轨交设备" },
  "01772": { group: "有色金属", detail: "能源金属" },
  "01787": { group: "有色金属", detail: "贵金属" },
  "01800": { group: "建筑装饰", detail: "基础建设" },
  "01801": { group: "医药生物", detail: "生物制品" },
  "01810": { group: "电子", detail: "消费电子" },
  "01882": { group: "机械设备", detail: "专用设备" },
  "01876": { group: "食品饮料", detail: "啤酒" },
  "01898": { group: "煤炭", detail: "煤炭开采" },
  "01913": { group: "纺织服饰", detail: "服装家纺" },
  "01928": { group: "社会服务", detail: "旅游及景区" },
  "01929": { group: "纺织服饰", detail: "饰品" },
  "01963": { group: "银行" },
  "01972": { group: "房地产", detail: "房地产开发" },
  "01988": { group: "银行" },
  "02007": { group: "房地产", detail: "房地产开发" },
  "02015": { group: "汽车", detail: "乘用车" },
  "02018": { group: "电子", detail: "消费电子" },
  "02020": { group: "纺织服饰", detail: "服装家纺" },
  "02050": { group: "家用电器", detail: "家电零部件" },
  "02057": { group: "交通运输", detail: "物流" },
  "02076": { group: "计算机", detail: "IT服务" },
  "02097": { group: "社会服务", detail: "酒店餐饮" },
  "02202": { group: "房地产", detail: "房地产开发" },
  "02208": { group: "电力设备", detail: "风电设备" },
  "02269": { group: "医药生物", detail: "生物制品" },
  "02313": { group: "纺织服饰", detail: "服装家纺" },
  "02318": { group: "非银金融", detail: "保险" },
  "02319": { group: "食品饮料", detail: "饮料乳品" },
  "02328": { group: "非银金融", detail: "保险" },
  "02331": { group: "纺织服饰", detail: "服装家纺" },
  "02333": { group: "汽车", detail: "乘用车" },
  "02338": { group: "汽车", detail: "汽车零部件" },
  "02357": { group: "国防军工", detail: "航空装备" },
  "02359": { group: "医药生物", detail: "医疗服务" },
  "02382": { group: "电子", detail: "光学光电子" },
  "02388": { group: "银行" },
  "02400": { group: "传媒", detail: "游戏" },
  "02423": { group: "房地产", detail: "房地产服务" },
  "02600": { group: "有色金属", detail: "工业金属" },
  "02601": { group: "非银金融", detail: "保险" },
  "02607": { group: "医药生物", detail: "医药商业" },
  "02611": { group: "非银金融", detail: "证券" },
  "02628": { group: "非银金融", detail: "保险" },
  "03288": { group: "食品饮料", detail: "调味发酵品" },
  "03328": { group: "银行" },
  "03606": { group: "汽车", detail: "汽车零部件" },
  "03618": { group: "银行" },
  "03690": { group: "商贸零售", detail: "互联网电商" },
  "03692": { group: "医药生物", detail: "化学制药" },
  "03698": { group: "银行" },
  "03750": { group: "电力设备", detail: "电池" },
  "03800": { group: "电力设备", detail: "光伏设备" },
  "03908": { group: "非银金融", detail: "证券" },
  "03968": { group: "银行" },
  "03988": { group: "银行" },
  "03993": { group: "有色金属", detail: "小金属" },
  "04336": { group: "电子", detail: "半导体" },
  "06030": { group: "非银金融", detail: "证券" },
  "06288": { group: "纺织服饰", detail: "服装家纺" },
  "06618": { group: "医药生物", detail: "医药商业" },
  "06690": { group: "家用电器", detail: "白色家电" },
  "06818": { group: "银行" },
  "06823": { group: "通信", detail: "通信服务" },
  "06865": { group: "电力设备", detail: "光伏设备" },
  "06881": { group: "非银金融", detail: "证券" },
  "06886": { group: "非银金融", detail: "证券" },
  "09618": { group: "商贸零售", detail: "互联网电商" },
  "09633": { group: "食品饮料", detail: "软饮料" },
  "09696": { group: "有色金属", detail: "能源金属" },
  "09866": { group: "汽车", detail: "乘用车" },
  "09868": { group: "汽车", detail: "乘用车" },
  "09888": { group: "传媒", detail: "数字媒体" },
  "09899": { group: "传媒", detail: "数字媒体" },
  "09901": { group: "社会服务", detail: "教育" },
  "09961": { group: "社会服务", detail: "旅游及景区" },
  "09987": { group: "社会服务", detail: "酒店餐饮" },
  "09988": { group: "商贸零售", detail: "互联网电商" },
  "09992": { group: "轻工制造", detail: "文娱用品" },
  "09999": { group: "传媒", detail: "游戏" },
};

const GENERIC_INDUSTRY_LABELS: Record<string, IndustryDisplay> = {
  可选消费: { group: "商贸零售" },
  必需消费: { group: "食品饮料" },
  消费品: { group: "食品饮料" },
  科技: { group: "计算机" },
  金融: { group: "非银金融" },
  医疗保健: { group: "医药生物" },
  零售: { group: "商贸零售", detail: "一般零售" },
  餐饮: { group: "社会服务", detail: "酒店餐饮" },
  能源: { group: "石油石化" },
  工业: { group: "机械设备" },
  原材料: { group: "基础化工" },
  公用事业: { group: "公用事业" },
  通信服务: { group: "通信", detail: "通信服务" },
};

export function localizedCompanyName(rawName: unknown, ticker: unknown, market: unknown) {
  const name = typeof rawName === "string" ? rawName.trim() : "";
  const code = localizedCodeKey(ticker, market);
  return (code && COMPANY_NAME_BY_CODE[code]) || name || (typeof ticker === "string" ? ticker.trim() : "");
}

export function localizedIndustry(ticker: unknown, market: unknown, industry?: unknown, sector?: unknown, fallback?: unknown) {
  const code = localizedCodeKey(ticker, market);
  const override = code ? INDUSTRY_BY_CODE[code] : undefined;
  if (override) return normalizeDisplay(override);

  const detail = normalizeIndustryLabel(industry) || normalizeIndustryLabel(sector);
  const fallbackDetail = normalizeIndustryLabel(fallback);
  const group = industryGroupForLabel(detail) || industryGroupForLabel(fallbackDetail);
  if (group) return normalizeDisplay({ group, detail: detail && detail !== group ? detail : undefined });

  const generic = (detail && GENERIC_INDUSTRY_LABELS[detail]) || (fallbackDetail && GENERIC_INDUSTRY_LABELS[fallbackDetail]);
  if (generic) return normalizeDisplay(generic);

  if (detail || fallbackDetail) return normalizeDisplay({ group: detail || fallbackDetail || UNKNOWN_INDUSTRY });
  return { group: UNKNOWN_INDUSTRY, detail: undefined };
}

export function formatLocalizedIndustry(industry: IndustryDisplay) {
  return formatIndustryLabel(industry.detail, industry.group);
}

function normalizeDisplay(industry: IndustryDisplay) {
  const group = normalizeIndustryLabel(industry.group) || UNKNOWN_INDUSTRY;
  const detail = normalizeIndustryLabel(industry.detail);
  return { group, detail: detail && detail !== group ? detail : undefined };
}

function localizedCodeKey(ticker: unknown, market: unknown) {
  const code = typeof ticker === "string" ? ticker.trim().toUpperCase() : "";
  if (!code) return "";
  if (isHongKongMarket(market) && /^\d{1,5}$/.test(code)) return code.padStart(5, "0");
  if (isUsMarket(market)) return code.replace(/[.-]/g, "_");
  return "";
}

function isHongKongMarket(market: unknown) {
  const text = typeof market === "string" ? market.toUpperCase() : "";
  return /港|HK|HONG/.test(text);
}

function isUsMarket(market: unknown) {
  const text = typeof market === "string" ? market.toUpperCase() : "";
  return /美|US|USA|NASDAQ|NYSE|AMEX/.test(text);
}
